config/routes.rb
Rails.application.routes.draw do
  get 'new' => 'contacts#new'

  root 'contacts#index'
  get 'show' => 'contacts#show'
  get 'name' => 'contacts#contacts_by_name'
  get 'cat' => 'contacts#contacts_by_category'
  get 'help' => 'contacts#help'
  get 'edit' => 'contacts#edit'
  get 'feedback' => 'contacts#feedback'
  
  # get "contacts/new" => 'contacts#new', :as => :new

  resources :contacts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :contacts
end

app/models/contact.rb
class Contact < ApplicationRecord
  geocoded_by :full_address
  after_validation :geocode

  def full_address
    return "#{address}, #{city}, #{state}"
  end

    belongs_to :category
    def self.search(term)
        if term
          where('name LIKE ?', "%#{term}%")
        else
          order('id DESC')
        end
    end
      
end

app/models/message.rb
class Message
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



  private

 

  def categories
    @categories = Category.contact(:name)
  end



end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :all_contacts, only: [:index, :create, :update, :show]
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  
  # So what's going on here? First, we expose the sort_column and sort_direction methods to our helpers. 
  # This allows us to utilize them outside the controller. Next, the index method orders by our current sort column 
  # (specified by the sort_column method) and direction (specified by the sort_direction method). If you take a 
  # look at the sort_column method you'll see that it checks the column names against a white list of column names.
  # This prevents the user from sorting by columns we may not wish to have them sort by, id for instance. The sort
  # direction method checks to make sure the direction is either asc or desc. Both methods return sensible defaults 
  # otherwise. This helps keep the user from doing unexpected things with your data. 
  helper_method :sort_column, :sort_direction

  # GET /contacts
  # GET /contacts.json


  # contacts = Contact.search(params[:term]).page(params[:page]).per(15)
  # @contacts = contacts.order("#{sort_column} #{sort_direction}")
  def all_contacts
    @contacts = Contact.all
    @contacts = Contact.order("#{sort_column} #{sort_direction}")
  end


  # GET /contacts/new
  def new
    @contact = Contact.new
    @categories = Category.all
  end

  # GET /contacts/1/edi
  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    @categories = Category.all


    respond_to do |format|
      if @contact.save
        # UserMailer.welcome_email(@user).deliver_now
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
end

  def show
    #@contacts = Contact.find(params[:id])
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # search methods to search by category or name
  def contacts_by_name
    @contacts = Contact.where(name: params[:name])
    @name = params[:name]
  end

  def contacts_by_category
    @contacts = Contact.where(category_id: params[:category_id])
    @categories = Category.where(params[:category])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    #sorting methods
    def sortable_columns
      ["Name"]
    end
  
    def sort_column
      sortable_columns.include?(params[:column]) ? params[:column] : "name"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :address, :city, :state, :zip, :phone, :category, :remarks, :category_id, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/contacts_helper.rb
module ContactsHelper

    # The sort_link method takes 2 arguments. The first, column, is the name of the column you wish to sort by. 
    # The next, title is the text based title of the column. This can be anything. If title is nil, the method 
    # will use the actual column name in Title Case. The rest of the code generates the css classes and the 
    # hyperlink. This gets returned to our view, which injects it on the page. 


      def sort_link(column, title = nil)
        title ||= column.titleize
        direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
        icon = sort_direction == "asc" ? "glyphicon glyphicon-chevron-up" : "glyphicon glyphicon-chevron-down"
        icon = column == sort_column ? icon : ""
        link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
      end


end

app/views/contacts/_form.html.erb
<div class="grid">
  <div class="left"></div>
  <div class="center">
      <%= form_with(model: contact, local: true) do |form| %>
        <% if contact.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

            <ul>
            <% contact.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
            <%= form.select :category_id, @categories.collect { |c| [c.name, c.id]}, {include_blank: 'Please select a category: ' } %>
        </div>

        <div class="form-group">
          <%= form.text_field :name.downcase, id: :contact_name, placeholder: "Name" %>
        </div>

        <div class="form-group">
          <%= form.text_field :email.downcase, id: :contact_email, placeholder: "Email" %>
        </div>

        <div class="form-group">
          <%= form.text_field :address.downcase, id: :contact_address, placeholder: "Address" %>
        </div>

        <div class="form-group">
          <%= form.text_field :city.downcase, id: :contact_city, placeholder: "City" %>
        </div>

        <div class="form-group">
          <%= form.text_field :state.downcase, id: :contact_state, placeholder: "State" %>
        </div>

        <div class="form-group">
          <%= form.text_field :zip, id: :contact_zip, placeholder: "Zip" %>
        </div>

        <div class="form-group">
          <%= form.text_field :phone, id: :contact_phone, placeholder: "Phone" %>
        </div>

        <div class="form-group">
          <%= form.text_area :remarks, id: :contact_remarks, placeholder: "Comments" %>
        </div>
        
        <div class="actions">
          <%= form.submit "Add to Contacts", class: 'actions-btn' %>
        </div><br><br>
      <% end %>
    </div>
    <div class="right"></div>

</div>

app/views/contacts/_search_loop.html.erb
<div class="row">

    <table class='table table-bordered table-striped'>
            <thead>
              <tr>
                <th><%= sort_link "Name" %></th>
                <th><%= sort_link "Category" %></th>
                <th>Email</th>
                <th>Phone</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          
            <tbody>
              <% @contacts.each do |contact| %>
                <tr>
                  <td><%= link_to contact.name, contact %></td>
                  <td><%= contact.category.name %></td>
                  <td><%= mail_to contact.email %></td>
                  <td><%= tel_to contact.phone %></td>
                  <td><%= link_to 'Edit', edit_contact_path(contact), class: "btn btn-xs btn-info" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          

</div>

app/views/contacts/contacts_by_category.html.erb
<h2>Your Search Results</h2>

<%= render 'search_loop' %>

app/views/contacts/contacts_by_name.html.erb
<h2>Your Search Results</h2>

<%= render 'search_loop' %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/feedback.html.erb
<h3>Contact Form</h3>

<div class="f-container">
        <form action="mailto:info@dropyard.io">
        <label for="fname">First Name</label>
        <input type="text" id="fname" name="firstname" placeholder="Your name..">

        <label for="lname">Last Name</label>
        <input type="text" id="lname" name="lastname" placeholder="Your last name..">

        <label for="country">Country</label>
        <select id="country" name="country">
            <option value="usa">USA</option>
            <option value="canada">Canada</option>
        </select>

        <label for="subject">Subject</label>
        <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

        <input type="submit" value="Submit">
    </form>
</div>

app/views/contacts/help.html.erb
<h1>Help</h1>


<div class="faq-container" style="border-top: 1px solid #cccc;">

    <h2>FAQ</h2>
    <ul class="help">
        <li class="faq"><a href='#sect-new'>How do I enter a new contact?</a></li>
        <li class="faq"><a href='#sect-acct'>How do I create a Drop Yard account?</a></li>
        <li class="faq"><a href='#sect-search'>How do I search for a contact?</a></li>
        <li class="faq"><a href='#sect-category'>How do I see my contacts by category?</a></li>
        <li class="faq"><a href='#sect-email'>How do I send a contact an email?</a></li>
        <li class="faq"><a href='#sect-call'>How do I call a contact from app?</a></li>
        <li class="faq"><a href='#sect-dy'>How do I contact Drop Yard?</a></li>
    </ul>

    <div id="sect-new">
        <h3>How do I enter a new contact?</h3>
        <p>
            From the menu select 'New Contact'.  Complete the new contact form, a category is required.
        </p>
    </div>
    <div id="sect-acct">
        <h3>How do I create a Drop Yard account?</h3>
        <p>
            creat your free accout by selecting 'Sign Up' button near the top of the page.
        </p>
    </div>

    <div id="sect-search">
        <h3>How do I search for a contact?</h3>
        <p>
            Feature unavailable at this time.
        </p>
    </div>
    <div id="sect-category">
        <h3>How do I see my contacts by category?</h3>
        <p>
            feature coming in future updates.
        </p>
    </div>
    <div id="sect-email">
        <h3>How do I send a contact an email?</h3>
        <p>
            find the contact you wish to email and click their email link.  Your local mail client will open with email address pre populated.
        </p>
    </div>
    <div id="sect-call">
        <h3>How do I call a contact from app?</h3>
        <p>
            Find Contact and click the phone number. If you are on a mobile device you will be able to dials contact.
        </p>
    </div>
    <div id="sect-dy">
        <h3>How do I contact Drop Yard?</h3>
        <p>
            Email <a href="mailto://info@dropyard.io">info@Dropyard.io</a>
        </p>
    </div>



</div>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>
<div class="index">
<h1>Contacts</h1>

<table class='table'>
  <thead>
    <tr>
      <th><%= sort_link "Name" %></th>
      <th>Category</th>
      <th>Email</th>
      <th>Phone</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.name, contact %></td>
        <td><%= contact.category.name %></td>
        <td><%= mail_to contact.email %></td>
        <td><%= tel_to contact.phone %></td>        
      </tr>
    <% end %>
  </tbody>
</table>
<!-- <div class="pagination">
    <%# paginate @contacts %>
</div> -->


</div>


<br>
<div class="footer-nav">
<%# link_to 'Add New Contact', new_contact_path, class: 'btn btn-sm btn-default new' %>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="grid show-page">
    <div class="show-page-left">
        <div class="panel">
          <div class="panel-heading">
              <strong><%= @contact.name.titleize %></strong> - <%= @contact.category.name.titleize %>
          </div>
          <div class="panel-body">
            <div class="wrapper-panel">
              <p class="showcontact">
                <%= @contact.address.titleize %><br>
                <%= @contact.city.titleize %>
                <%= @contact.state.upcase %>&nbsp;&nbsp;
                <%= @contact.zip %><br><br>
                <small><%= mail_to @contact.email.upcase %></small><br>
                <%= tel_to number_to_phone(@contact.phone) %>
              </p>
            </div>
            <div class="w3-panel remark-panel">
                <p>
                    <%= @contact.remarks %>
                </p>
            </div>
          </div>

        </div>

        <div class="footer-nav">
          <%= link_to 'Edit', edit_contact_path(@contact), class: 'btn btn-sx btn-default' %>
          <%= link_to 'Delete', contact_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sx btn-default' %>
          <%= link_to 'Back', contacts_path, class: 'btn btn-sx btn-default' %>
        </div>
                  <!-- <div class="clearfix"></div> -->
                  <%= javascript_tag do %>
                    var latitude = '<%= j @contact.latitude.to_s %>';
                    var longitude = '<%= j @contact.longitude.to_s %>';
                    var address = '<%= j @contact.city.to_s %>';
                  <% end %>



        </div>
        <div class="show-grid-right">
            <div id="map-canvas"></div>
        </div>

    <!-- <div class="show-grid-right"></div -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dyfinal</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Eczar|Lora:700|Roboto+Slab" rel="stylesheet">   </head>

  <body>
    <div class="container jumbo">
      <div class="jumbotron">
        <h1><span>Drop Yard</span></h1>
      </div>
    </div>
    <div class="header-search">
        <nav class="navbar navbar-default" role="navigation">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Drop Yard", contacts_path, class: "navbar-brand" %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="#">Login</a></li>
                    <li><a href="#">Sign Out</a></li>
                    <li><a href="#">Sign Up</a></li>                   
                </ul>
                <div class="col-sm-3 col-md-3 pull-right">
                    <form class="navbar-form" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search" name="q">
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>        
            </div>
        </nav>
      </div>
      <div id="wrapper" class="">
                <div  class="open">
                  <span class="cls"></span>
                  <span>
                    <ul class="sub-menu ">
                      <li>
                        <%= link_to "Home", contacts_path, class: "home" %>
                      </li>
                      <li>
                        <%= link_to 'New Contact', new_contact_path, class: 'new' %>
                      </li>
                      <li>
                        <%= link_to "Feedback", feedback_path, class: "Feedback" %>
                      </li>
                      <li>
                        <%= link_to "Help", help_path, class: "help" %>
                      </li>
                    </ul>
                  </span>
                  <span class="cls"></span>

              </div>
              <div class="content-container">
                  <%= yield %>
              </div>

              <div class="map"></div>
              
            </div>
            <footer class="footer">
                <div class="grid">
                  <div class="left">
                    <div class="social">
                      <ul>
                        <li>Facebook</li>
                        <li>Twitter</li>
                        <li>Github</li>
                      </ul>
                    </div>
                  </div>
              
                  <div class="center"></div>
              
                  <div class="right">
                    <div class="legal">
                      <ul>
                        <li><p>&copy; 2018. All Rights Reserved</p></li>
                        <li><p></p></li>
                        <li>Created by:&nbsp;  <a href="mailto://odloads@live.com">Jesse Hatton</a></li>
                      </ul>
                    </div>
                  </div>
              </div>
              </footer>


  <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= Figaro.env.google_api_key %>"></script>
  </body>
</html>